package com.example.k_gallery.presentation.util

sealed class NavHelper(var route:String){
    object SplashScreen: NavHelper("splash")
    object DetailsScreen: NavHelper("detail")
    object FoldersScreen: NavHelper("folders")
    object ImageScreen: NavHelper("image")
    object HomeScreen: NavHelper("home")
    object PhotosScreen: NavHelper("photos")
    object PhotosImageScreen: NavHelper("photosImage")
    object VideoHomeScreen: NavHelper("videoHomeScreen")
    object VideosInFolderScreen: NavHelper("videosInFolderScreen")
    object VideoScreen: NavHelper("videoScreen")
    object AllVideosScreen: NavHelper("videoScreen")
    object MultipleVideoScreen: NavHelper("videoScreen")
    object FavoriteScreen: NavHelper("favoriteScreen")
    object OnboardingScreen: NavHelper("onboardingScreen")
    object GetStartedScreen: NavHelper("getStartedScreen")
    object ChoiceScreen: NavHelper("choiceScreen")
    object LoginScreen: NavHelper("loginScreen")
    object SignupScreen: NavHelper("signupScreen")
    object VerifyEmailScreen: NavHelper("verifyEmailScreen")
    object VerifyForgotPasswordTokenScreen: NavHelper("verifyForgotPasswordTokenScreen")
    object UpdateUserPasswordScreen: NavHelper("updateUserPasswordScreen")
    object UpdateUserDetailScreen:NavHelper("updateUserDetailsScreen")
    object CompleteRegistrationScreen:NavHelper("completeRegistrationScreen")
    object HomeDashBoardScreenScreen: NavHelper("homeDashBoardScreen")
    object ForgotPasswordScreen: NavHelper("forgotPassword")
    object CompleteForgotPasswordScreen: NavHelper("completeForgotPassword")
    object HomeOnlineScreen: NavHelper("homeOnlineScreen")
    object SavedMediaScreen: NavHelper("savedMediaScreen")
    object SendMediaScreen: NavHelper("sendMediaScreen")
    object OnlineFavoriteScreen: NavHelper("OnlineFavoriteScreen")
    object UserScreen: NavHelper("UserScreen")
    object AuthScreens: NavHelper("AuthScreens")
}
